[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/.netlify/functions/:name"
to = "/.netlify/functions/:name"
status = 200

[functions]
external_node_modules = ["@supabase/supabase-js"]

[context.production.environment]
VITE_SUPABASE_URL = ""
VITE_SUPABASE_ANON_KEY = ""

[context.deploy-preview.environment]
VITE_SUPABASE_URL = ""
VITE_SUPABASE_ANON_KEY = ""
